identifier: k6wcq4o0e53ctf18
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: decentral-school
homeFolder: C:\Users\ad358\workspace\DecentralSchoolRepo\decentral-school
distFolder: dist/decentral-school
outDir: C:\Users\ad358\workspace\DecentralSchoolRepo\decentral-school\dist\static
handle404: ''
allowErrorCollect: false
